### PR TITLE
Removed Backend Code from Master and Documentation Update

### LINKED ISSUE #39: Remove the backend code from master.
As master is only responsbile for frontend, 

We need to remove all unnecessary folders which were earlier used to host backend.

Only Client folder should not be deleted.

### PR DESCRIPTION
**Pull request by imabp**
Fixes #39 and #38

### CODE REVIEW

**Comment by imabp** [comment]
@tarunnsingh I have removed the backend code from master thats why nodejs CI is failing, and as I have done no changes, in client folder, so the deploy preview is cancelled

I think, we should turn off nodeJS CLI for master, and only put it for v1-deployment

**Comment by tarunnsingh** [comment]
> @tarunnsingh I have removed the backend code from master thats why nodejs CI is failing, and as I have done no changes, in client folder, so the deploy preview is cancelled
> 
> I think, we should turn off nodeJS CLI for master, and only put it for v1-deployment

Sure Doing that.

**Comment by tarunnsingh** [comment]
Hey @imabp I removed the CI tests, where can I find these NEtlify Rules?

**Comment by imabp** [comment]
@tarunnsingh Netlify is already installed. Here is SS
image

**Comment by imabp** [comment]
@tarunnsingh I have updated the readme too. And removed the backend code.

**Comment by imabp** [comment]
@tarunnsingh  any problem facing in merging this issue, do tell me. I will make changes then 😅😅😅

**Comment by tarunnsingh** [comment]
> @tarunnsingh any problem facing in merging this issue, do tell me. I will make changes then 😅😅😅

No worries, was a bit involved elsewhere, doing it now.

**Review by tarunnsingh — APPROVED** [review]

**Comment by tarunnsingh** [comment]
@all-contributors please add @imabp for doc

**Comment by imabp** [comment]
@all-contributors 
What all you can do ?? 🙄

**Comment by imabp** [comment]
@all-contributors add @imabp for infra

He has setup up deployment pipeline 🤣

**Comment by imabp** [comment]
Ohh  @all-contributors, you are damn funny. 
I meant infrastructure ! 🙄🙄

**Comment by tarunnsingh** [comment]
Haha ya 😆 

> @all-contributors add @imabp for infra
> 
> He has setup up deployment pipeline 🤣

**Comment by imabp** [comment]
awww @all-contributors ..

@tarunnsingh atleast, yeh toh bhaav de rha hai 🤣🤣🤣

**Comment by tarunnsingh** [comment]
Hey @imabp I small question, how would we be running the whole app locally, I mean, we can have the latest server from `v1-deployment` separately and the client from `master` in a separate terminal (let's say). 

Perhaps there is no way to run the latest version of the app together from a single terminal?
Please let me know on this.

**Comment by imabp** [comment]
@tarunnsingh I am trying to figure out a solution for this. 

For now, I am using `git stash` , `git  stash pop` and in between `git stash list`

Also before using stash, I have to do git add to untracked folders.. extra unnecessary work I am doing.. 😔😔

Only one solution I could figure out like having a complete different repo dedicated for backend.. But that is not a good idea now 😓😓

**Pull request merged**
