### PR TITLE
Route Updated for Image Fetching

### PR DESCRIPTION
**Pull request by imabp**
I have modified posts route in route folder.

In this I added a route for eventImages to fetch event images only.. Past and present event.

@tarunnsingh , for now its okay . But for future. I think, there can be better system design for fetching images, one cannot code at frontend every time for new upcoming event.

### CODE REVIEW

**Comment by imabp** [comment]
@tarunnsingh  after you merge this PR then only merge my frontend PR which I am going to send soon

**Comment by tarunnsingh** [comment]
@imabp 
### Well actually when I created this website, it was more of a temporary arrangement to just put out blogs. I had no idea that it will grow such big and itself become an organization.
So yes many big changes were required, and thanks for bringing them in. 

### Once you are done with your changes and PRs, let me know as I have a lot of local work that would need to be refactored and updated accordingly.

**Comment by imabp** [comment]
Thankyou @tarunnsingh for your kind words. I am obliged.
I am happy that I learnt a lot while contributing to this repo.  And lot to learn more 😊😊

Finally Image fetching stuff is fixed now. 
I am sending two PRs again for `v1-deployment` and `master` as had to do some fixes in both the part.

image

**Comment by imabp** [comment]
@tarunnsingh label this one also as `hacktoberfest-accepted` and the final PRs here : #70  #71

**Pull request merged**
