### PR TITLE
Axios and Project Structure Changed

### PR DESCRIPTION
**Pull request by imabp**
Everything works fine, except Images

image

### CODE REVIEW

**Comment by imabp** [comment]
Dont merge now, I am not facing issue in local deployment but in production deployment, the axios is not working :(

**Comment by imabp** [comment]
Perfect things are working now. You can merge it @tarunnsingh ... 😊😊😊😊

**Comment by imabp** [comment]
Major Issue is fonts 
image

**Comment by imabp** [comment]
@tarunnsingh  These two images are not found on server. 
So that is why it is not rendered

image

**Comment by imabp** [comment]
@tarunnsingh I dont know, but are we using Google Analytics ? The requests I think are put up in public/index.html page.
image

**Comment by imabp** [comment]
Well except all these errors.. the deploy preview page looks like this now

**Comment by imabp** [comment]
Well @tarunnsingh we can merge it, and then we will set up the get request for images as described in #63

**Comment by tarunnsingh** [comment]
image
@imabp 
Have a close look, that none of the images are actually being pulled from server.
2 Images under the banner are there on server [see here](https://github.com/alexa-dev-hub/alexa-community-jaipur/tree/v1-deployment/routes/event-images).

Next we also have images inside each blog post which are again not being fetched. And they are also there on server [see here](https://github.com/alexa-dev-hub/alexa-community-jaipur/tree/v1-deployment/routes/images).

So overall the client side even with this PR stands same at where it is currently. 😕

**Comment by imabp** [comment]
@tarunnsingh I am implementing a useImageFetch hook

**Comment by imabp** [comment]
Hey @tarunnsingh I am on it. Implementing it. Image fetching had a dry test its working. will push to v1-deployment. Some changes are required there too. 

image

**Comment by imabp** [comment]
@tarunnsingh can u merge this PR, I will send back fresh PR again with image changes only. ? 
As in this PR I have changed the directory structure and hooks implemented

**Comment by tarunnsingh** [comment]
OKay!

**Comment by imabp** [comment]
@tarunnsingh one more request, can you label all the PRs sent , from Oct 1 as `hacktoberfest-accepted`

Here are my set of PRs on and after Oct 1.

#33  #34  #36  #40  #61 #67

**Comment by tarunnsingh** [comment]
Done!

**Pull request merged**
