### PR TITLE
Add Contributors to README.md

### LINKED ISSUE #15: Add the list of contributors in the readme.md file
List out all the contributors to this repository and auto-add all the contributors
Go through this https://github.com/all-contributors/all-contributors for more information

### PR DESCRIPTION
**Pull request by hariom1625**
I have made use of all-contributors CLI to add the contributors to the README.md file. And have initially added those contributors who have contributed to this repo till now.

### CODE REVIEW

**Comment by hariom1625** [comment]
Now to keep updating the contributor's list in  the README.md file there are two ways:
1) Using CLI
2) Using all-contributors bot

So to update using the CLI you have to simply run the command in your root directory
``` yarn all-contributors add <username> <contributions (emoji key)> ```
``` yarn all-contributors generate ```
And that's all :-) , the markdown file will get updated.

Now coming to the second method i.e using Bot
I would personally recommend you to use this for updating the list.
For this, you will simply need to visit this link: https://allcontributors.org/docs/en/bot/installation
Then, click on ```Install the GitHub App```, then simply select the repo on which you want to install the bot.
That's it, the bot will get installed :-)
So, now if you want to add any person in the contributor's list, You will simply need to comment under the merged PR or Issue or anywhere ```@all-contributors please add <username> for <contributions> ```
Then the bot will automatically create a PR to add that person onto the list.

PS: The emoji key means the emoticon that is being visible below your name on the README.md file there are quite a few emoji keys that you can look after in the official documentation. I am attaching the link for the same (https://allcontributors.org/docs/en/emoji-key)

**Comment by sumanthst24** [comment]
I have checked everything but I think there is a problem with the line below
[All Contributors](#contributors-)
Its directly displaying the URL in the readme file .
Once look into it @hariom1625

**Comment by sumanthst24** [comment]
Screenshot (1)
It's displaying the contributors URL in the readme file.
Try to fix this

**Comment by hariom1625** [comment]
> Screenshot (1)
> It's displaying the contributors URL in the readme file.
> Try to fix this

Sure, have a look at the latest commit :-)

**Review by sumanthst24 — COMMENTED** [review]
Now its fine

**Comment by sumanthst24** [comment]
@tarunnsingh you can merge this PR now

**Comment by tarunnsingh** [comment]
@hariom1625 What do I need to replace `<contributions>` with in `@all-contributors please add <username> for <contributions>`

**Comment by hariom1625** [comment]
You will have to replace the ```<contributions>``` with the type of contribution the individual has contributed to.
For eg: if he/she had fixed a bug or helped in doc or wrote a code you can simple write 

``` @all-contributors please add <username> for code ```

So a emoticon resembling code will be added below his/her name in the markdown file :-)

You can look up for more emoji key here 
(https://allcontributors.org/docs/en/emoji-key)

**Comment by tarunnsingh** [comment]
Oh Got it Thanks!

**Comment by tarunnsingh** [comment]
@all-contributors please add @hariom1625  for code

**Comment by tarunnsingh** [comment]
@all-contributors please add @hariom1625 for code

**Comment by hariom1625** [comment]
> Now to keep updating the contributor's list in  the README.md file there are two ways:
> 1) Using CLI
> 2) Using all-contributors bot
> 
> So to update using the CLI you have to simply run the command in your root directory
> ``` yarn all-contributors add <username> <contributions (emoji key)> ```
> ``` yarn all-contributors generate ```
> And that's all :-) , the markdown file will get updated.
> 
> Now coming to the second method i.e using Bot
> I would personally recommend you to use this for updating the list.
> For this, you will simply need to visit this link: https://allcontributors.org/docs/en/bot/installation
> Then, click on ```Install the GitHub App```, then simply select the repo on which you want to install the bot.
> That's it, the bot will get installed :-)
> So, now if you want to add any person in the contributor's list, You will simply need to comment under the merged PR or Issue or anywhere ```@all-contributors please add <username> for <contributions> ```
> Then the bot will automatically create a PR to add that person onto the list.
> 
> PS: The emoji key means the emoticon that is being visible below your name on the README.md file there are quite a few emoji keys that you can look after in the official documentation. I am attaching the link for the same (https://allcontributors.org/docs/en/emoji-key)

@tarunnsingh, You will need to first install the app and enable the bot in your repo.Kindly go through the steps and the link i have mentioned here :-)

**Pull request merged**
