### PR TITLE
logo of Alexa Dev Hub Added

### LINKED ISSUE #19: Create/Design a LOGO
### Current Website Heading is a Simple/Boring Text 🔽 
image

### PR DESCRIPTION
**Pull request by ManojAthreya**
Fixes #19 
 Created a logo for Alexa Dev Hub.

### CODE REVIEW

**Comment by tarunnsingh** [comment]
image
#### That looks just okay.
If you could replace the central Red Object with an Echo Dot, that would look more elegant. 
Another suggestion: It's better to write **DEV** instead of just **</>** although you can make use of **/>** which looks like a **D** in DEV.
_All your efforts are appreciated!!_ 🔥 

@sumanthst24 could you suggest on this.

**Comment by ManojAthreya** [comment]
Thanks for your suggestion will try to improve it.

**Comment by ManojAthreya** [comment]
Fixes #19 
Added new logo

**Review by tarunnsingh — APPROVED** [review]
Looks Good.

**Comment by tarunnsingh** [comment]
@all-contributors please add @ManojAthreya for design

**Pull request merged**
