### PR TITLE
V1 deployment

### PR DESCRIPTION
**Pull request by imabp**
# V1 deployment page updated.

image

### CODE REVIEW

**Comment by imabp** [comment]
@tarunnsingh I have a doubt

**Comment by imabp** [comment]
Did you check, `v1-deployment` branch is hosted on heroku

**Comment by imabp** [comment]
I think, dynos need to restarted or what ? I cannot see the changes at 
alexadevhub.herokuapp.com

**Comment by tarunnsingh** [comment]
> @tarunnsingh I have a doubt

What is it ?

**Comment by tarunnsingh** [comment]
https://alexadevhub.herokuapp.com/
Looks good.

**Comment by imabp** [comment]
@tarunnsingh The doubt is, we dont need backend files on master. So we should remove it.
Plus we should turn off github actions nodejs cli for master, as we have installed netlify

**Pull request merged**
